server:
   port: 9093
   servlet:
      context-path: /auth
spring:
   profiles: dev
   application:
      name: auth-server
   main:
     allow-bean-definition-overriding: true
   jpa:
      properties:
         hibernate:
            dialect: org.hibernate.dialect.H2Dialect
      hibernate:
         naming:
            physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
         ddl-auto: validate
      show-sql: true
   datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:Authentification;
      username: sa
      password:
   liquibase:
      enabled: true
      drop-first: true
      change-log: classpath:/db/changelog/db.changelog-master.xml
   h2:
      console:
         enabled: true
   mail:
      host: smtp.gmail.com
      port: 587
      username: arsel.cm@gmail.com
      password: xdGnKL4m5x8wiJkMd8bx
      properties:
         mail:
            smtp:
               auth: true
               connectiontimeout: 5000
               timeout: 5000
               writetimeout: 5000
               starttls:
                  enable: true
   mvc:
      async:
         request-timeout: 5000
eureka:
   instance:
      hostname: localhost
      port: 9091
   client:
      serviceUrl:
         defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
logging:
   level:
      root: INFO

properties:
   cors:
      access-control-allow-origin: http://localhost:4200
      access-control-allow-methods: POST, GET, OPTIONS, DELETE, PUT
      access-control-max-age: 3600
      access-control-allow-headers: x-requested-with, authorization, content-type