server:
   port: 9093
   use-forward-headers: false
   servlet:
      context-path: /auth
spring:
   profiles: prd
   application:
      name: auth-server
   main:
     allow-bean-definition-overriding: true
   jpa:
      properties:
         hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
         naming:
            physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
         ddl-auto: validate
   datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/Authentification?useSSL=false
      username: litige
      password: litige
   liquibase:
      enabled: true
      drop-first: true
      change-log: classpath:db/changelog/db.changelog-master.xml
   mail:
      host: smtp.gmail.com
      port: 587
      username: arsel.cm@gmail.com
      password: xdGnKL4m5x8wiJkMd8bx
      properties:
         mail:
            smtp:
               auth: true
               connectiontimeout: 5000
               timeout: 5000
               writetimeout: 5000
               starttls:
                  enable: true
   mvc:
      async:
         request-timeout: 5000
eureka:
   instance:
      hostname: localhost
      port: 9091
   client:
      serviceUrl:
         defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
logging:
   level:
      root: INFO
      liquibase: DEBUG