version: '3'

services:
  eureka:
    image: litige/eureka:latest
    ports:
      - "9091:9091"
    networks:
      - litige-backend
  zuul:
    image: litige/zuul:latest
    ports:
      - "9092:9092"
    links:
      - eureka
    networks:
      - litige-backend
  authorization:
    image: litige/authorization:latest
    ports:
      - "9093:9093"
    links:
      - eureka
      - zuul
    networks:
      - litige-backend
  resource-1:
    image: litige/resource-1:latest
    ports:
      - "9094:9094"
    links:
      - eureka
      - zuul
  front:
    image: litige/front:latest
    ports:
      - "4200:80"
    links:
      - eureka
      - zuul
      - authorization
      - resource-1
    networks:
      - litige-backend
networks:
  litige-backend:
    driver: "bridge"