spring:
  application:
    name: zuul
  profiles: default
    
server:
  port: 9092

  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
      
zuul:
  ignoredServices: "*"
  routes:
    resource-server-1:
      sensitiveHeaders:
      path: /api/**
      serviceId: resource-server-1  
    auth-server:  
      sensitiveHeaders:
      path: /security/**
      stripPrefix: false
      serviceId: auth-server
      sensitive-headers: Cookie,Set-Cookie,Authorization   
eureka:
  instance:
    hostname: localhost
    port: 9091
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/



hystrix:
   command:
      default:
         execution:
            isolation:
               thread:
                  timeoutInMilliseconds: 1000000
            strategy: THREAD

ribbon:
   ReadTimeout: 60000