spring:
   application:
      name: zuul
   profiles: default
   mvc:
      dispatch-options-request: true
   http:
      multipart:
        max-file-size: 16MB
        max-request-size: 16MB
server:
   port: 9092
endpoints:
   restart:
      enabled: true
   shutdown:
      enabled: true
   health:
      sensitive: false
logging:
   level:
      root: INFO
zuul:
   debug:
      request: true
   ignoredServices: '*'
   ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
   routes:
      resource-server-1:
         sensitiveHeaders: null
         path: /api/**
         serviceId: resource-server-1
         stripPrefix: false
      auth-server:
         sensitiveHeaders: null
         path: /auth/**
         serviceId: auth-server
         stripPrefix: false
ribbon:
   ConnectTimeout: 3000
   ReadTimeout: 60000
eureka:
   instance:
      hostname: localhost
      port: 9091
   client:
      serviceUrl:
         defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
properties:
   front-server-name: angular
   cors:
      access-control-allow-origin: http://localhost:4200
      access-control-allow-methods: POST, GET, OPTIONS, DELETE, PUT
      access-control-max-age: 3600
      access-control-allow-headers: x-requested-with, authorization, content-type