spring:
  application:
    name: zuul
  profiles: default
      
server:
  port: 9092
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
      
zuul:
  ignoredServices: '*'
  routes:
    resource-server-1:
      sensitiveHeaders:
      path: /api/**
      serviceId: resource-server-1  
      stripPrefix: false
    auth-server:
      sensitiveHeaders:
      path: /uaa/**
      serviceId: auth-server
      stripPrefix: false
eureka:
  instance:
    hostname: localhost
    port: 9091
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/