spring:
  application:
    name: eureka-server 
  profiles: default

server:
  port: 9091

eureka:
  client:
    registerWithEureka: false #telling the server not to register himself in the service registry
    fetchRegistry: false
