spring:
  application:
    name: eureka-server
  profiles: docker

server:
  port: 9091

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false #telling the server not to register himself in the service registry
    fetchRegistry: false
  server:
    wait-time-in-ms-when-sync-empty: 3000