server:
   port: 9094
   servlet:
      context-path: /api
   compression:
      enabled: false
management:
   security:
      enabled: false
auth-server:
   url: http://localhost:9093
spring:
   profiles: default
   application:
      name: resource-server-1
   jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      show-sql: false
   datasource:
      url: jdbc:h2:mem:testdb
      driverClassName: org.h2.Driver
      username: sa
      password: password
   h2:
      console:
         enabled: true
#  jpa:
   jackson:
      property-naming-strategy: SNAKE_CASE
      serialization:
#    database: H2
#    show-sql: true
#    properties:
#      hibernate:
#       format_sql: true
#    hibernate:
#      ddl-auto: create
#  datasource:
#    url: jdbc:h2:mem:got;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    username: sa
#    password: sa
#    driver-class-name: org.h2.Driver
         indent-output: true
eureka:
   instance:
      hostname: localhost
      port: 9091
   client:
      serviceUrl:
         defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/