server:
   port: 9094
   servlet:
      context-path: /api
   compression:
      enabled: false
management:
   security:
      enabled: false
auth-server:
   url: http://localhost:9093
spring:
   profiles: default
   application:
      name: resource-server-1
   jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      show-sql: false
   datasource:
      url: jdbc:h2:mem:testdb
      driverClassName: org.h2.Driver
      username: sa
      password: password
   h2:
      console:
         enabled: true
#  jpa:
   jackson:
      property-naming-strategy: SNAKE_CASE
      serialization:
#    database: H2
         indent-output: true
eureka:
   instance:
      hostname: localhost
      port: 9091
   client:
      registerWithEureka: true
      fetchRegistry: false
      serviceUrl:
         defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
   server:
      wait-time-in-ms-when-sync-empty: 3000
      

logging:
  level:
    root: INFO