spring:
   security:
      user:   
         name: user
         password: password
      sessions: NEVER    
configuration:
    cors: # CORS is enable in dev mode to allow cromeFront (localhost:4200) to communicate with the back (localhost:8080)
        allowed-origins: "http://localhost:8080"
        allowed-methods: GET, PUT, POST, DELETE, OPTIONS
        allowed-headers: "*"
        exposed-headers:
        allow-credentials: true
        max-age: 1800