# spring:
#    security:
#       user:   
#          name: user
#          password: password
#       sessions: NEVER    
# configuration:
#     cors: # CORS is enable in dev mode to allow cromeFront (localhost:4200) to communicate with the back (localhost:8080)
#         allowed-origins: "http://localhost:8080"
#         allowed-methods: GET, PUT, POST, DELETE, OPTIONS
#         allowed-headers: "*"
#         exposed-headers:
#         allow-credentials: true
#         max-age: 1800

spring:
   datasource: 
      username: postgres
      password: postgres
      url: jdbc:postgresql://localhost:5432/test
   jpa:
      show-sql: true
      properties:
         hibernate:
            jdbc:
               lob:
                  non_contextual_creation: true
   user:
       datasource:
          driver-class-name: org.postgresql.Driver
#spring.jpa.hibernate.ddl-auto=create
#spring.user.datasource.driver-class-name=com.mysql.jdbc.Driver
#spring.user.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true