spring:
   jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      show-sql: false
   datasource:
      url: jdbc:h2:mem:testdb
      driverClassName: org.h2.Driver
      username: sa
      password: password
   h2:
      console:
         enabled: true
jwt:
   clientId: glee-o-meter
   client-secret: secret
#    show-sql: false
   accessTokenValidititySeconds: 100
   refreshTokenValiditySeconds: 1000

server:
  port: 9999
  use-forward-headers: false
  servlet:
    context-path: /uaa
  

eureka:
  instance:
    hostname: localhost
    port: 9091
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server: 
    wait-time-in-ms-when-sync-empty: 3000
   